name: Deploy Frontend
on:
  push:
    branches:
      - main
env:
  SHA: $(git rev-parse HEAD)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - run: docker login -u ${{secrets.DOCKER_USERNAME}} - p ${{secrets.DOCKER_PASSWORD}}

    - name: Login to dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

    # building

    - name: Build
      run: |-
          docker build -t amasaabubakar/multi-client-k8s-gh:latest -t amasaabubakar/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t amasaabubakar/multi-server-k8s-pgfix-gh:latest -t amasaabubakar/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t amasaabubakar/multi-worker-k8s-gh:latest -t amasaabubakar/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
        
    - name: Push
      run: |-
          docker push amasaabubakar/multi-client-k8s-gh:latest
          docker push amasaabubakar/multi-server-k8s-pgfix-gh:latest
          docker push amasaabubakar/multi-worker-k8s-gh:latest
 
          docker push amasaabubakar/multi-client-k8s-gh:${{ env.SHA }}
          docker push amasaabubakar/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push amasaabubakar/multi-worker-k8s-gh:${{ env.SHA }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
      run: aws eks --region us-east-1 update-kubeconfig --name multi-cluster


    
    - name: Apply
      run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=cygnetops/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=cygnetops/multi-worker-k8s-gh:${{ env.SHA }}
